//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyApp.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add contact.
        /// </summary>
        internal static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact has been added successfully!.
        /// </summary>
        internal static string AddContactOkay {
            get {
                return ResourceManager.GetString("AddContactOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add event.
        /// </summary>
        internal static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has been added successfully!.
        /// </summary>
        internal static string AddEventOkay {
            get {
                return ResourceManager.GetString("AddEventOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add transaction.
        /// </summary>
        internal static string AddTransaction {
            get {
                return ResourceManager.GetString("AddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction has been added successfully!.
        /// </summary>
        internal static string AddTransactionOkay {
            get {
                return ResourceManager.GetString("AddTransactionOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name cannot contain more than 100 symbols!.
        /// </summary>
        internal static string ContactNameMaxLengthError {
            get {
                return ResourceManager.GetString("ContactNameMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name cannot be empty!.
        /// </summary>
        internal static string ContactNameWrong {
            get {
                return ResourceManager.GetString("ContactNameWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully!.
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit contact.
        /// </summary>
        internal static string EditContact {
            get {
                return ResourceManager.GetString("EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact has been edited successfully!.
        /// </summary>
        internal static string EditContactOkay {
            get {
                return ResourceManager.GetString("EditContactOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit event.
        /// </summary>
        internal static string EditEvent {
            get {
                return ResourceManager.GetString("EditEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has been edited successfully!.
        /// </summary>
        internal static string EditEventOkay {
            get {
                return ResourceManager.GetString("EditEventOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit recurring event.
        /// </summary>
        internal static string EditRecurringEvent {
            get {
                return ResourceManager.GetString("EditRecurringEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring event has been edited successfully!.
        /// </summary>
        internal static string EditRecurringEventOkay {
            get {
                return ResourceManager.GetString("EditRecurringEventOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit recurring transaction.
        /// </summary>
        internal static string EditRecurringTransaction {
            get {
                return ResourceManager.GetString("EditRecurringTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring transaction has been edited successfully!.
        /// </summary>
        internal static string EditRecurringTransactionOkay {
            get {
                return ResourceManager.GetString("EditRecurringTransactionOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit transaction.
        /// </summary>
        internal static string EditTransaction {
            get {
                return ResourceManager.GetString("EditTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction has been edited successfully!.
        /// </summary>
        internal static string EditTransactionOkay {
            get {
                return ResourceManager.GetString("EditTransactionOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty!.
        /// </summary>
        internal static string ErrorEmptyName {
            get {
                return ResourceManager.GetString("ErrorEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring events.
        /// </summary>
        internal static string RecurringEvents {
            get {
                return ResourceManager.GetString("RecurringEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring transactions.
        /// </summary>
        internal static string RecurringTransactions {
            get {
                return ResourceManager.GetString("RecurringTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        internal static string SomethingError {
            get {
                return ResourceManager.GetString("SomethingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
    }
}
